/**
 * @file switch.h
 * @brief Central Switch header. Includes all others.
 * @copyright libnx Authors
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "nx/types.h"
#include "nx/result.h"

#include "nx/nro.h"
#include "nx/nacp.h"

#include "nx/arm/tls.h"
#include "nx/arm/cache.h"
#include "nx/arm/counter.h"

#include "nx/kernel/svc.h"
#include "nx/kernel/wait.h"
#include "nx/kernel/tmem.h"
#include "nx/kernel/shmem.h"
#include "nx/kernel/mutex.h"
#include "nx/kernel/event.h"
#include "nx/kernel/levent.h"
#include "nx/kernel/uevent.h"
#include "nx/kernel/utimer.h"
#include "nx/kernel/rwlock.h"
#include "nx/kernel/condvar.h"
#include "nx/kernel/thread.h"
#include "nx/kernel/semaphore.h"
#include "nx/kernel/virtmem.h"
#include "nx/kernel/detect.h"
#include "nx/kernel/random.h"
#include "nx/kernel/jit.h"
#include "nx/kernel/barrier.h"

#include "nx/sf/hipc.h"
#include "nx/sf/cmif.h"
#include "nx/sf/service.h"
#include "nx/sf/sessionmgr.h"
#include "nx/sf/tipc.h"

#include "nx/services/sm.h"
#include "nx/services/smm.h"
#include "nx/services/fs.h"
#include "nx/services/fsldr.h"
#include "nx/services/fspr.h"
#include "nx/services/acc.h"
#include "nx/services/apm.h"
#include "nx/services/applet.h"
#include "nx/services/async.h"
#include "nx/services/audctl.h"
#include "nx/services/audin.h"
#include "nx/services/audout.h"
#include "nx/services/audrec.h"
#include "nx/services/audren.h"
#include "nx/services/auddev.h"
#include "nx/services/hwopus.h"
#include "nx/services/csrng.h"
#include "nx/services/lbl.h"
#include "nx/services/i2c.h"
#include "nx/services/gpio.h"
#include "nx/services/uart.h"
#include "nx/services/bpc.h"
#include "nx/services/pcv.h"
#include "nx/services/clkrst.h"
#include "nx/services/fan.h"
#include "nx/services/pgl.h"
#include "nx/services/psm.h"
#include "nx/services/spsm.h"
//#include "nx/services/bsd.h" Use <sys/socket.h> instead
//#include "nx/services/sfdnsres.h" Use <netdb.h> instead
//#include "nx/services/htcs.h"
#include "nx/services/fatal.h"
#include "nx/services/time.h"
#include "nx/services/usb.h"
#include "nx/services/usbds.h"
#include "nx/services/usbhs.h"
#include "nx/services/hid.h"
#include "nx/services/hidbus.h"
#include "nx/services/hiddbg.h"
#include "nx/services/hidsys.h"
#include "nx/services/irs.h"
#include "nx/services/pl.h"
#include "nx/services/vi.h"
#include "nx/services/nv.h"
#include "nx/services/nifm.h"
#include "nx/services/nim.h"
#include "nx/services/ns.h"
#include "nx/services/ldr.h"
#include "nx/services/ro.h"
#include "nx/services/tc.h"
#include "nx/services/ts.h"
#include "nx/services/pm.h"
#include "nx/services/set.h"
#include "nx/services/ssl.h"
#include "nx/services/lr.h"
#include "nx/services/bt.h"
#include "nx/services/btdrv.h"
#include "nx/services/btm.h"
#include "nx/services/btmu.h"
#include "nx/services/btmsys.h"
#include "nx/services/spl.h"
#include "nx/services/ncm.h"
#include "nx/services/psc.h"
#include "nx/services/caps.h"
#include "nx/services/capsa.h"
#include "nx/services/capsc.h"
#include "nx/services/capsdc.h"
#include "nx/services/capsu.h"
#include "nx/services/capssc.h"
#include "nx/services/capssu.h"
#include "nx/services/capmtp.h"
#include "nx/services/nfc.h"
#include "nx/services/wlaninf.h"
#include "nx/services/pctl.h"
#include "nx/services/pdm.h"
#include "nx/services/grc.h"
#include "nx/services/friends.h"
#include "nx/services/notif.h"
#include "nx/services/mii.h"
#include "nx/services/miiimg.h"
#include "nx/services/ldn.h"
#include "nx/services/lp2p.h"
#include "nx/services/news.h"
#include "nx/services/ins.h"
#include "nx/services/ectx.h"
#include "nx/services/avm.h"
#include "nx/services/mm.h"

#include "nx/display/binder.h"
#include "nx/display/parcel.h"
#include "nx/display/buffer_producer.h"
#include "nx/display/native_window.h"
#include "nx/display/framebuffer.h"

#include "nx/nvidia/ioctl.h"
#include "nx/nvidia/graphic_buffer.h"
#include "nx/nvidia/fence.h"
#include "nx/nvidia/map.h"
#include "nx/nvidia/address_space.h"
#include "nx/nvidia/channel.h"
#include "nx/nvidia/gpu.h"
#include "nx/nvidia/gpu_channel.h"

#include "nx/audio/driver.h"

#include "nx/applets/libapplet.h"
#include "nx/applets/album_la.h"
#include "nx/applets/friends_la.h"
#include "nx/applets/hid_la.h"
#include "nx/applets/mii_la.h"
#include "nx/applets/nfp_la.h"
#include "nx/applets/nifm_la.h"
#include "nx/applets/pctlauth.h"
#include "nx/applets/psel.h"
#include "nx/applets/error.h"
#include "nx/applets/swkbd.h"
#include "nx/applets/web.h"

#include "nx/runtime/env.h"
#include "nx/runtime/hosversion.h"
#include "nx/runtime/diag.h"
#include "nx/runtime/nxlink.h"
#include "nx/runtime/resolver.h"
#include "nx/runtime/pad.h"
#include "nx/runtime/ringcon.h"
#include "nx/runtime/btdev.h"

#include "nx/runtime/util/utf.h"

#include "nx/runtime/devices/console.h"
#include "nx/runtime/devices/usb_comms.h"
#include "nx/runtime/devices/fs_dev.h"
#include "nx/runtime/devices/romfs_dev.h"
#include "nx/runtime/devices/socket.h"

#include "nx/crypto/aes.h"
#include "nx/crypto/aes_cbc.h"
#include "nx/crypto/aes_ctr.h"
#include "nx/crypto/aes_xts.h"
#include "nx/crypto/cmac.h"

#include "nx/crypto/sha256.h"
#include "nx/crypto/sha1.h"
#include "nx/crypto/hmac.h"

#include "nx/crypto/crc.h"

#ifdef __cplusplus
}
#endif

